### ISSUE TITLE
Unable to install the extension

### ISSUE THREAD

**Issue by piotrd** [Ghirro/graphql-network#10]
I use Chrome 60.0.3112.78 (macOS Sierra 10.12.6). This extension doesn't seem to be compatible with Chrome anymore. When I try to install it, after a while I get the following error message:

> Could not install package: 'UTILITY_PROCESS_CRASHED_WHILE_TRYING_TO_INSTALL'. Could not install package because a utility process crashed. Try restarting chrome and trying again.

Any tips? Workarounds? @Ghirro

**Comment by ntziolis** [comment]
I'm cleanup up issues, where you able to install it?
