### ISSUE TITLE
Support form data?

### ISSUE THREAD

**Issue by rmosolgo** [Ghirro/graphql-network#4]
Hi there! I was just trying out this extension but I found that my queries don't show up. 

I see there are two ways for it to find queries: `POST` with a `query` in the JSON body; or `Content-Type=application/graphql`. I'm not sure if it's possible, but I'd like my queries to show up, but they work differently. 

I'm using jQuery to send AJAX requests, basically like this: 

``` js
$.post(
  graphqlURL, 
  {
    query: queryString, 
    variables: JSON.stringify(queryVariables)
  },
  responseHandlerFunction
)
```

By default, jQuery turns the parameters into Form Data, so my network tab looks like this: 

![image](https://cloud.githubusercontent.com/assets/2231765/19040154/f020e97a-8950-11e6-8ba8-d6b74548c029.png)

(The `Content-Type` is `application/json; charset=utf-8`)

Is it possible to support this in the extension? Thanks for considering it!

**Comment by Ghirro** [comment]
Hi there,

I'll mark this for the next release version as it's a good point. I'm sure there's got to be a better way of discerning whether or not a query is GraphQL and I'll give it a go. I won't be able to get round ti it for a couple of weeks but in the meantime:

https://github.com/Ghirro/graphql-network/blob/master/src/lib/utils.js#L75

That's where the code that determines whether the query is valid as GraphQL (`isGraphQL`) and then `parseEntry` does the initial retrieval of the query. If you want to fork and patch yourself feel free.

**Comment by Ghirro** [comment]
Should now be supported

**Comment by rmosolgo** [comment]
Thanks, I look forward to giving it a try!!
